# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  csharpdocker:
    image: csharpdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            #user is sa
            SA_PASSWORD: "123pwd123"
            ACCEPT_EULA: "Y"